source 'https://rubygems.org'

# Specify your gem's dependencies in compass-core.gemspec
gemspec

gem 'pry'
gem 'diff-lcs', '~> 1.1.2'
gem 'true', "~> 0.2.3"
gem 'timecop', "~> 0.9.0"
gem 'test-unit', '~> 3.6.0'
